language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker

before_install:
  - docker build -t legan/docker-react -f Dockerfile.dev .

script:
  - docker run legan/docker-react npm run test -- --exit